language: node_js

branches:
    only:
        - master

node_js:
    - '8'

cache: yarn

install:
    - yarn global add firebase-tools

after_success:
    - firebase deploy —-project $FIREBASE_PROJECT —-token $FIREBASE_TOKEN
